var Reactions;
(Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.Reaction = exports.Reactions = void 0),
  ((o) => {
    ((o.HEART = "/-heart"),
      (o.LIKE = "/-strong"),
      (o.HAHA = ":>"),
      (o.WOW = ":o"),
      (o.CRY = ":-(("),
      (o.ANGRY = ":-h"),
      (o.KISS = ":-*"),
      (o.TEARS_OF_JOY = ":')"),
      (o.SHIT = "/-shit"),
      (o.ROSE = "/-rose"),
      (o.BROKEN_HEART = "/-break"),
      (o.DISLIKE = "/-weak"),
      (o.LOVE = ";xx"),
      (o.CONFUSED = ";-/"),
      (o.WINK = ";-)"),
      (o.FADE = "/-fade"),
      (o.SUN = "/-li"),
      (o.BIRTHDAY = "/-bd"),
      (o.BOMB = "/-bome"),
      (o.OK = "/-ok"),
      (o.PEACE = "/-v"),
      (o.THANKS = "/-thanks"),
      (o.PUNCH = "/-punch"),
      (o.SHARE = "/-share"),
      (o.PRAY = "_()_"),
      (o.NO = "/-no"),
      (o.BAD = "/-bad"),
      (o.LOVE_YOU = "/-loveu"),
      (o.SAD = "--b"),
      (o.VERY_SAD = ":(("),
      (o.COOL = "x-)"),
      (o.NERD = "8-)"),
      (o.BIG_SMILE = ";-d"),
      (o.SUNGLASSES = "b-)"),
      (o.NEUTRAL = ":--|"),
      (o.SAD_FACE = "p-("),
      (o.BYE = ":-bye"),
      (o.SLEEPY = "|-)"),
      (o.WIPE = ":wipe"),
      (o.DIG = ":-dig"),
      (o.ANGUISH = "&-("),
      (o.HANDCLAP = ":handclap"),
      (o.ANGRY_FACE = ">-|"),
      (o.F_CHAIR = ":-f"),
      (o.L_CHAIR = ":-l"),
      (o.R_CHAIR = ":-r"),
      (o.SILENT = ";-x"),
      (o.SURPRISE = ":-o"),
      (o.EMBARRASSED = ";-s"),
      (o.AFRAID = ";-a"),
      (o.SAD2 = ":-<"),
      (o.BIG_LAUGH = ":))"),
      (o.RICH = "$-)"),
      (o.BEER = "/-beer"),
      (o.NONE = ""));
  })(Reactions || (exports.Reactions = Reactions = {})));
class Reaction {
  constructor(o, e, R) {
    ((this.data = e),
      (this.threadId = R || "0" == e.uidFrom ? e.idTo : e.uidFrom),
      (this.isSelf = "0" == e.uidFrom),
      (this.isGroup = R),
      "0" == e.idTo && (e.idTo = o),
      "0" == e.uidFrom && (e.uidFrom = o));
  }
}
exports.Reaction = Reaction;
