var BusinessCategory;
(Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.BusinessCategoryName = exports.BusinessCategory = void 0),
  ((e) => {
    ((e[(e.Other = 0)] = "Other"),
      (e[(e.RealEstate = 1)] = "RealEstate"),
      (e[(e.TechnologyAndDevices = 2)] = "TechnologyAndDevices"),
      (e[(e.TravelAndHospitality = 3)] = "TravelAndHospitality"),
      (e[(e.EducationAndTraining = 4)] = "EducationAndTraining"),
      (e[(e.ShoppingAndRetail = 5)] = "ShoppingAndRetail"),
      (e[(e.CosmeticsAndBeauty = 6)] = "CosmeticsAndBeauty"),
      (e[(e.RestaurantAndCafe = 7)] = "RestaurantAndCafe"),
      (e[(e.AutoAndMotorbike = 8)] = "AutoAndMotorbike"),
      (e[(e.FashionAndApparel = 9)] = "FashionAndApparel"),
      (e[(e.FoodAndBeverage = 10)] = "FoodAndBeverage"),
      (e[(e.MediaAndEntertainment = 11)] = "MediaAndEntertainment"),
      (e[(e.InternalCommunications = 12)] = "InternalCommunications"),
      (e[(e.Transportation = 13)] = "Transportation"),
      (e[(e.Telecommunications = 14)] = "Telecommunications"));
  })(BusinessCategory || (exports.BusinessCategory = BusinessCategory = {})),
  (exports.BusinessCategoryName = {
    [BusinessCategory.Other]: "Dịch vụ khác (Không hiển thị)",
    [BusinessCategory.RealEstate]: "Bất động sản",
    [BusinessCategory.TechnologyAndDevices]: "Công nghệ & Thiết bị",
    [BusinessCategory.TravelAndHospitality]: "Du lịch & Lưu trú",
    [BusinessCategory.EducationAndTraining]: "Giáo dục & Đào tạo",
    [BusinessCategory.ShoppingAndRetail]: "Mua sắm & Bán lẻ",
    [BusinessCategory.CosmeticsAndBeauty]: "Mỹ phẩm & Làm đẹp",
    [BusinessCategory.RestaurantAndCafe]: "Nhà hàng & Quán",
    [BusinessCategory.AutoAndMotorbike]: "Ô tô & Xe máy",
    [BusinessCategory.FashionAndApparel]: "Thời trang & May mặc",
    [BusinessCategory.FoodAndBeverage]: "Thực phẩm & Đồ uống",
    [BusinessCategory.MediaAndEntertainment]: "Truyền thông & Giải trí",
    [BusinessCategory.InternalCommunications]: "Truyền thông nội bộ",
    [BusinessCategory.Transportation]: "Vận tải",
    [BusinessCategory.Telecommunications]: "Viễn thông",
  }));
