(Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.API = void 0));
let listen_js_1 = require("./apis/listen.js"),
  acceptFriendRequest_js_1 = require("./apis/acceptFriendRequest.js"),
  addGroupBlockedMember_js_1 = require("./apis/addGroupBlockedMember.js"),
  addGroupDeputy_js_1 = require("./apis/addGroupDeputy.js"),
  addPollOptions_js_1 = require("./apis/addPollOptions.js"),
  addQuickMessage_js_1 = require("./apis/addQuickMessage.js"),
  addReaction_js_1 = require("./apis/addReaction.js"),
  addUnreadMark_js_1 = require("./apis/addUnreadMark.js"),
  addUserToGroup_js_1 = require("./apis/addUserToGroup.js"),
  blockUser_js_1 = require("./apis/blockUser.js"),
  blockViewFeed_js_1 = require("./apis/blockViewFeed.js"),
  changeAccountAvatar_js_1 = require("./apis/changeAccountAvatar.js"),
  changeFriendAlias_js_1 = require("./apis/changeFriendAlias.js"),
  changeGroupAvatar_js_1 = require("./apis/changeGroupAvatar.js"),
  changeGroupName_js_1 = require("./apis/changeGroupName.js"),
  changeGroupOwner_js_1 = require("./apis/changeGroupOwner.js"),
  createAutoReply_js_1 = require("./apis/createAutoReply.js"),
  createCatalog_js_1 = require("./apis/createCatalog.js"),
  createGroup_js_1 = require("./apis/createGroup.js"),
  createNote_js_1 = require("./apis/createNote.js"),
  createPoll_js_1 = require("./apis/createPoll.js"),
  createProductCatalog_js_1 = require("./apis/createProductCatalog.js"),
  createReminder_js_1 = require("./apis/createReminder.js"),
  deleteAutoReply_js_1 = require("./apis/deleteAutoReply.js"),
  deleteAvatar_js_1 = require("./apis/deleteAvatar.js"),
  deleteCatalog_js_1 = require("./apis/deleteCatalog.js"),
  deleteChat_js_1 = require("./apis/deleteChat.js"),
  deleteGroupInviteBox_js_1 = require("./apis/deleteGroupInviteBox.js"),
  deleteMessage_js_1 = require("./apis/deleteMessage.js"),
  deleteProductCatalog_js_1 = require("./apis/deleteProductCatalog.js"),
  disableGroupLink_js_1 = require("./apis/disableGroupLink.js"),
  disperseGroup_js_1 = require("./apis/disperseGroup.js"),
  editNote_js_1 = require("./apis/editNote.js"),
  editReminder_js_1 = require("./apis/editReminder.js"),
  enableGroupLink_js_1 = require("./apis/enableGroupLink.js"),
  fetchAccountInfo_js_1 = require("./apis/fetchAccountInfo.js"),
  findUser_js_1 = require("./apis/findUser.js"),
  forwardMessage_js_1 = require("./apis/forwardMessage.js"),
  getAliasList_js_1 = require("./apis/getAliasList.js"),
  getAllFriends_js_1 = require("./apis/getAllFriends.js"),
  getAllGroups_js_1 = require("./apis/getAllGroups.js"),
  getArchivedChatList_js_1 = require("./apis/getArchivedChatList.js"),
  getAutoDeleteChat_js_1 = require("./apis/getAutoDeleteChat.js"),
  getAutoReplyList_js_1 = require("./apis/getAutoReplyList.js"),
  getAvatarList_js_1 = require("./apis/getAvatarList.js"),
  getBizAccount_js_1 = require("./apis/getBizAccount.js"),
  getCatalogList_js_1 = require("./apis/getCatalogList.js"),
  getContext_js_1 = require("./apis/getContext.js"),
  getCookie_js_1 = require("./apis/getCookie.js"),
  getFriendBoardList_js_1 = require("./apis/getFriendBoardList.js"),
  getFriendOnlines_js_1 = require("./apis/getFriendOnlines.js"),
  getFriendRecommendations_js_1 = require("./apis/getFriendRecommendations.js"),
  getFriendRequestStatus_js_1 = require("./apis/getFriendRequestStatus.js"),
  getGroupBlockedMember_js_1 = require("./apis/getGroupBlockedMember.js"),
  getGroupInfo_js_1 = require("./apis/getGroupInfo.js"),
  getGroupInviteBoxInfo_js_1 = require("./apis/getGroupInviteBoxInfo.js"),
  getGroupInviteBoxList_js_1 = require("./apis/getGroupInviteBoxList.js"),
  getGroupLinkDetail_js_1 = require("./apis/getGroupLinkDetail.js"),
  getGroupLinkInfo_js_1 = require("./apis/getGroupLinkInfo.js"),
  getGroupMembersInfo_js_1 = require("./apis/getGroupMembersInfo.js"),
  getHiddenConversations_js_1 = require("./apis/getHiddenConversations.js"),
  getLabels_js_1 = require("./apis/getLabels.js"),
  getListBoard_js_1 = require("./apis/getListBoard.js"),
  getListReminder_js_1 = require("./apis/getListReminder.js"),
  getMute_js_1 = require("./apis/getMute.js"),
  getOwnId_js_1 = require("./apis/getOwnId.js"),
  getPendingGroupMembers_js_1 = require("./apis/getPendingGroupMembers.js"),
  getPinConversations_js_1 = require("./apis/getPinConversations.js"),
  getPollDetail_js_1 = require("./apis/getPollDetail.js"),
  getProductCatalogList_js_1 = require("./apis/getProductCatalogList.js"),
  getQR_js_1 = require("./apis/getQR.js"),
  getQuickMessageList_js_1 = require("./apis/getQuickMessageList.js"),
  getRelatedFriendGroup_js_1 = require("./apis/getRelatedFriendGroup.js"),
  getReminder_js_1 = require("./apis/getReminder.js"),
  getReminderResponses_js_1 = require("./apis/getReminderResponses.js"),
  getSentFriendRequest_js_1 = require("./apis/getSentFriendRequest.js"),
  getSettings_js_1 = require("./apis/getSettings.js"),
  getStickers_js_1 = require("./apis/getStickers.js"),
  getStickersDetail_js_1 = require("./apis/getStickersDetail.js"),
  getUnreadMark_js_1 = require("./apis/getUnreadMark.js"),
  getUserInfo_js_1 = require("./apis/getUserInfo.js"),
  inviteUserToGroups_js_1 = require("./apis/inviteUserToGroups.js"),
  joinGroupInviteBox_js_1 = require("./apis/joinGroupInviteBox.js"),
  joinGroupLink_js_1 = require("./apis/joinGroupLink.js"),
  keepAlive_js_1 = require("./apis/keepAlive.js"),
  lastOnline_js_1 = require("./apis/lastOnline.js"),
  leaveGroup_js_1 = require("./apis/leaveGroup.js"),
  lockPoll_js_1 = require("./apis/lockPoll.js"),
  parseLink_js_1 = require("./apis/parseLink.js"),
  rejectFriendRequest_js_1 = require("./apis/rejectFriendRequest.js"),
  removeFriend_js_1 = require("./apis/removeFriend.js"),
  removeFriendAlias_js_1 = require("./apis/removeFriendAlias.js"),
  removeGroupBlockedMember_js_1 = require("./apis/removeGroupBlockedMember.js"),
  removeGroupDeputy_js_1 = require("./apis/removeGroupDeputy.js"),
  removeQuickMessage_js_1 = require("./apis/removeQuickMessage.js"),
  removeReminder_js_1 = require("./apis/removeReminder.js"),
  removeUnreadMark_js_1 = require("./apis/removeUnreadMark.js"),
  removeUserFromGroup_js_1 = require("./apis/removeUserFromGroup.js"),
  resetHiddenConversPin_js_1 = require("./apis/resetHiddenConversPin.js"),
  reuseAvatar_js_1 = require("./apis/reuseAvatar.js"),
  reviewPendingMemberRequest_js_1 = require("./apis/reviewPendingMemberRequest.js"),
  sendBankCard_js_1 = require("./apis/sendBankCard.js"),
  sendCard_js_1 = require("./apis/sendCard.js"),
  sendDeliveredEvent_js_1 = require("./apis/sendDeliveredEvent.js"),
  sendFriendRequest_js_1 = require("./apis/sendFriendRequest.js"),
  sendLink_js_1 = require("./apis/sendLink.js"),
  sendMessage_js_1 = require("./apis/sendMessage.js"),
  sendReport_js_1 = require("./apis/sendReport.js"),
  sendSeenEvent_js_1 = require("./apis/sendSeenEvent.js"),
  sendSticker_js_1 = require("./apis/sendSticker.js"),
  sendTypingEvent_js_1 = require("./apis/sendTypingEvent.js"),
  sendVideo_js_1 = require("./apis/sendVideo.js"),
  sendVoice_js_1 = require("./apis/sendVoice.js"),
  setHiddenConversations_js_1 = require("./apis/setHiddenConversations.js"),
  setMute_js_1 = require("./apis/setMute.js"),
  setPinnedConversations_js_1 = require("./apis/setPinnedConversations.js"),
  sharePoll_js_1 = require("./apis/sharePoll.js"),
  unblockUser_js_1 = require("./apis/unblockUser.js"),
  undo_js_1 = require("./apis/undo.js"),
  undoFriendRequest_js_1 = require("./apis/undoFriendRequest.js"),
  updateActiveStatus_js_1 = require("./apis/updateActiveStatus.js"),
  updateAutoDeleteChat_js_1 = require("./apis/updateAutoDeleteChat.js"),
  updateAutoReply_js_1 = require("./apis/updateAutoReply.js"),
  updateCatalog_js_1 = require("./apis/updateCatalog.js"),
  updateGroupSettings_js_1 = require("./apis/updateGroupSettings.js"),
  updateHiddenConversPin_js_1 = require("./apis/updateHiddenConversPin.js"),
  updateLabels_js_1 = require("./apis/updateLabels.js"),
  updateLang_js_1 = require("./apis/updateLang.js"),
  updateProductCatalog_js_1 = require("./apis/updateProductCatalog.js"),
  updateProfile_js_1 = require("./apis/updateProfile.js"),
  updateQuickMessage_js_1 = require("./apis/updateQuickMessage.js"),
  updateSettings_js_1 = require("./apis/updateSettings.js"),
  uploadAttachment_js_1 = require("./apis/uploadAttachment.js"),
  uploadProductPhoto_js_1 = require("./apis/uploadProductPhoto.js"),
  votePoll_js_1 = require("./apis/votePoll.js"),
  custom_js_1 = require("./apis/custom.js");
class API {
  constructor(e, t, s) {
    ((this.zpwServiceMap = t),
      (this.listener = new listen_js_1.Listener(e, s)),
      (this.acceptFriendRequest = (0,
      acceptFriendRequest_js_1.acceptFriendRequestFactory)(e, this)),
      (this.addGroupBlockedMember = (0,
      addGroupBlockedMember_js_1.addGroupBlockedMemberFactory)(e, this)),
      (this.addGroupDeputy = (0, addGroupDeputy_js_1.addGroupDeputyFactory)(
        e,
        this,
      )),
      (this.addPollOptions = (0, addPollOptions_js_1.addPollOptionsFactory)(
        e,
        this,
      )),
      (this.addQuickMessage = (0, addQuickMessage_js_1.addQuickMessageFactory)(
        e,
        this,
      )),
      (this.addReaction = (0, addReaction_js_1.addReactionFactory)(e, this)),
      (this.addUnreadMark = (0, addUnreadMark_js_1.addUnreadMarkFactory)(
        e,
        this,
      )),
      (this.addUserToGroup = (0, addUserToGroup_js_1.addUserToGroupFactory)(
        e,
        this,
      )),
      (this.blockUser = (0, blockUser_js_1.blockUserFactory)(e, this)),
      (this.blockViewFeed = (0, blockViewFeed_js_1.blockViewFeedFactory)(
        e,
        this,
      )),
      (this.changeAccountAvatar = (0,
      changeAccountAvatar_js_1.changeAccountAvatarFactory)(e, this)),
      (this.changeFriendAlias = (0,
      changeFriendAlias_js_1.changeFriendAliasFactory)(e, this)),
      (this.changeGroupAvatar = (0,
      changeGroupAvatar_js_1.changeGroupAvatarFactory)(e, this)),
      (this.changeGroupName = (0, changeGroupName_js_1.changeGroupNameFactory)(
        e,
        this,
      )),
      (this.changeGroupOwner = (0,
      changeGroupOwner_js_1.changeGroupOwnerFactory)(e, this)),
      (this.createAutoReply = (0, createAutoReply_js_1.createAutoReplyFactory)(
        e,
        this,
      )),
      (this.createCatalog = (0, createCatalog_js_1.createCatalogFactory)(
        e,
        this,
      )),
      (this.createGroup = (0, createGroup_js_1.createGroupFactory)(e, this)),
      (this.createNote = (0, createNote_js_1.createNoteFactory)(e, this)),
      (this.createPoll = (0, createPoll_js_1.createPollFactory)(e, this)),
      (this.createProductCatalog = (0,
      createProductCatalog_js_1.createProductCatalogFactory)(e, this)),
      (this.createReminder = (0, createReminder_js_1.createReminderFactory)(
        e,
        this,
      )),
      (this.deleteAutoReply = (0, deleteAutoReply_js_1.deleteAutoReplyFactory)(
        e,
        this,
      )),
      (this.deleteAvatar = (0, deleteAvatar_js_1.deleteAvatarFactory)(e, this)),
      (this.deleteCatalog = (0, deleteCatalog_js_1.deleteCatalogFactory)(
        e,
        this,
      )),
      (this.deleteChat = (0, deleteChat_js_1.deleteChatFactory)(e, this)),
      (this.deleteGroupInviteBox = (0,
      deleteGroupInviteBox_js_1.deleteGroupInviteBoxFactory)(e, this)),
      (this.deleteMessage = (0, deleteMessage_js_1.deleteMessageFactory)(
        e,
        this,
      )),
      (this.deleteProductCatalog = (0,
      deleteProductCatalog_js_1.deleteProductCatalogFactory)(e, this)),
      (this.disableGroupLink = (0,
      disableGroupLink_js_1.disableGroupLinkFactory)(e, this)),
      (this.disperseGroup = (0, disperseGroup_js_1.disperseGroupFactory)(
        e,
        this,
      )),
      (this.editNote = (0, editNote_js_1.editNoteFactory)(e, this)),
      (this.editReminder = (0, editReminder_js_1.editReminderFactory)(e, this)),
      (this.enableGroupLink = (0, enableGroupLink_js_1.enableGroupLinkFactory)(
        e,
        this,
      )),
      (this.fetchAccountInfo = (0,
      fetchAccountInfo_js_1.fetchAccountInfoFactory)(e, this)),
      (this.findUser = (0, findUser_js_1.findUserFactory)(e, this)),
      (this.forwardMessage = (0, forwardMessage_js_1.forwardMessageFactory)(
        e,
        this,
      )),
      (this.getAliasList = (0, getAliasList_js_1.getAliasListFactory)(e, this)),
      (this.getAllFriends = (0, getAllFriends_js_1.getAllFriendsFactory)(
        e,
        this,
      )),
      (this.getAllGroups = (0, getAllGroups_js_1.getAllGroupsFactory)(e, this)),
      (this.getArchivedChatList = (0,
      getArchivedChatList_js_1.getArchivedChatListFactory)(e, this)),
      (this.getAutoDeleteChat = (0,
      getAutoDeleteChat_js_1.getAutoDeleteChatFactory)(e, this)),
      (this.getAutoReplyList = (0,
      getAutoReplyList_js_1.getAutoReplyListFactory)(e, this)),
      (this.getAvatarList = (0, getAvatarList_js_1.getAvatarListFactory)(
        e,
        this,
      )),
      (this.getBizAccount = (0, getBizAccount_js_1.getBizAccountFactory)(
        e,
        this,
      )),
      (this.getCatalogList = (0, getCatalogList_js_1.getCatalogListFactory)(
        e,
        this,
      )),
      (this.getContext = (0, getContext_js_1.getContextFactory)(e, this)),
      (this.getCookie = (0, getCookie_js_1.getCookieFactory)(e, this)),
      (this.getFriendBoardList = (0,
      getFriendBoardList_js_1.getFriendBoardListFactory)(e, this)),
      (this.getFriendOnlines = (0,
      getFriendOnlines_js_1.getFriendOnlinesFactory)(e, this)),
      (this.getFriendRecommendations = (0,
      getFriendRecommendations_js_1.getFriendRecommendationsFactory)(e, this)),
      (this.getFriendRequestStatus = (0,
      getFriendRequestStatus_js_1.getFriendRequestStatusFactory)(e, this)),
      (this.getGroupBlockedMember = (0,
      getGroupBlockedMember_js_1.getGroupBlockedMemberFactory)(e, this)),
      (this.getGroupInfo = (0, getGroupInfo_js_1.getGroupInfoFactory)(e, this)),
      (this.getGroupInviteBoxInfo = (0,
      getGroupInviteBoxInfo_js_1.getGroupInviteBoxInfoFactory)(e, this)),
      (this.getGroupInviteBoxList = (0,
      getGroupInviteBoxList_js_1.getGroupInviteBoxListFactory)(e, this)),
      (this.getGroupLinkDetail = (0,
      getGroupLinkDetail_js_1.getGroupLinkDetailFactory)(e, this)),
      (this.getGroupLinkInfo = (0,
      getGroupLinkInfo_js_1.getGroupLinkInfoFactory)(e, this)),
      (this.getGroupMembersInfo = (0,
      getGroupMembersInfo_js_1.getGroupMembersInfoFactory)(e, this)),
      (this.getHiddenConversations = (0,
      getHiddenConversations_js_1.getHiddenConversationsFactory)(e, this)),
      (this.getLabels = (0, getLabels_js_1.getLabelsFactory)(e, this)),
      (this.getListBoard = (0, getListBoard_js_1.getListBoardFactory)(e, this)),
      (this.getListReminder = (0, getListReminder_js_1.getListReminderFactory)(
        e,
        this,
      )),
      (this.getMute = (0, getMute_js_1.getMuteFactory)(e, this)),
      (this.getOwnId = (0, getOwnId_js_1.getOwnIdFactory)(e, this)),
      (this.getPendingGroupMembers = (0,
      getPendingGroupMembers_js_1.getPendingGroupMembersFactory)(e, this)),
      (this.getPinConversations = (0,
      getPinConversations_js_1.getPinConversationsFactory)(e, this)),
      (this.getPollDetail = (0, getPollDetail_js_1.getPollDetailFactory)(
        e,
        this,
      )),
      (this.getProductCatalogList = (0,
      getProductCatalogList_js_1.getProductCatalogListFactory)(e, this)),
      (this.getQR = (0, getQR_js_1.getQRFactory)(e, this)),
      (this.getQuickMessageList = (0,
      getQuickMessageList_js_1.getQuickMessageListFactory)(e, this)),
      (this.getRelatedFriendGroup = (0,
      getRelatedFriendGroup_js_1.getRelatedFriendGroupFactory)(e, this)),
      (this.getReminder = (0, getReminder_js_1.getReminderFactory)(e, this)),
      (this.getReminderResponses = (0,
      getReminderResponses_js_1.getReminderResponsesFactory)(e, this)),
      (this.getSentFriendRequest = (0,
      getSentFriendRequest_js_1.getSentFriendRequestFactory)(e, this)),
      (this.getSettings = (0, getSettings_js_1.getSettingsFactory)(e, this)),
      (this.getStickers = (0, getStickers_js_1.getStickersFactory)(e, this)),
      (this.getStickersDetail = (0,
      getStickersDetail_js_1.getStickersDetailFactory)(e, this)),
      (this.getUnreadMark = (0, getUnreadMark_js_1.getUnreadMarkFactory)(
        e,
        this,
      )),
      (this.getUserInfo = (0, getUserInfo_js_1.getUserInfoFactory)(e, this)),
      (this.inviteUserToGroups = (0,
      inviteUserToGroups_js_1.inviteUserToGroupsFactory)(e, this)),
      (this.joinGroupInviteBox = (0,
      joinGroupInviteBox_js_1.joinGroupInviteBoxFactory)(e, this)),
      (this.joinGroupLink = (0, joinGroupLink_js_1.joinGroupLinkFactory)(
        e,
        this,
      )),
      (this.keepAlive = (0, keepAlive_js_1.keepAliveFactory)(e, this)),
      (this.lastOnline = (0, lastOnline_js_1.lastOnlineFactory)(e, this)),
      (this.leaveGroup = (0, leaveGroup_js_1.leaveGroupFactory)(e, this)),
      (this.lockPoll = (0, lockPoll_js_1.lockPollFactory)(e, this)),
      (this.parseLink = (0, parseLink_js_1.parseLinkFactory)(e, this)),
      (this.rejectFriendRequest = (0,
      rejectFriendRequest_js_1.rejectFriendRequestFactory)(e, this)),
      (this.removeFriend = (0, removeFriend_js_1.removeFriendFactory)(e, this)),
      (this.removeFriendAlias = (0,
      removeFriendAlias_js_1.removeFriendAliasFactory)(e, this)),
      (this.removeGroupBlockedMember = (0,
      removeGroupBlockedMember_js_1.removeGroupBlockedMemberFactory)(e, this)),
      (this.removeGroupDeputy = (0,
      removeGroupDeputy_js_1.removeGroupDeputyFactory)(e, this)),
      (this.removeQuickMessage = (0,
      removeQuickMessage_js_1.removeQuickMessageFactory)(e, this)),
      (this.removeReminder = (0, removeReminder_js_1.removeReminderFactory)(
        e,
        this,
      )),
      (this.removeUnreadMark = (0,
      removeUnreadMark_js_1.removeUnreadMarkFactory)(e, this)),
      (this.removeUserFromGroup = (0,
      removeUserFromGroup_js_1.removeUserFromGroupFactory)(e, this)),
      (this.resetHiddenConversPin = (0,
      resetHiddenConversPin_js_1.resetHiddenConversPinFactory)(e, this)),
      (this.reuseAvatar = (0, reuseAvatar_js_1.reuseAvatarFactory)(e, this)),
      (this.reviewPendingMemberRequest = (0,
      reviewPendingMemberRequest_js_1.reviewPendingMemberRequestFactory)(
        e,
        this,
      )),
      (this.sendBankCard = (0, sendBankCard_js_1.sendBankCardFactory)(e, this)),
      (this.sendCard = (0, sendCard_js_1.sendCardFactory)(e, this)),
      (this.sendDeliveredEvent = (0,
      sendDeliveredEvent_js_1.sendDeliveredEventFactory)(e, this)),
      (this.sendFriendRequest = (0,
      sendFriendRequest_js_1.sendFriendRequestFactory)(e, this)),
      (this.sendLink = (0, sendLink_js_1.sendLinkFactory)(e, this)),
      (this.sendMessage = (0, sendMessage_js_1.sendMessageFactory)(e, this)),
      (this.sendReport = (0, sendReport_js_1.sendReportFactory)(e, this)),
      (this.sendSeenEvent = (0, sendSeenEvent_js_1.sendSeenEventFactory)(
        e,
        this,
      )),
      (this.sendSticker = (0, sendSticker_js_1.sendStickerFactory)(e, this)),
      (this.sendTypingEvent = (0, sendTypingEvent_js_1.sendTypingEventFactory)(
        e,
        this,
      )),
      (this.sendVideo = (0, sendVideo_js_1.sendVideoFactory)(e, this)),
      (this.sendVoice = (0, sendVoice_js_1.sendVoiceFactory)(e, this)),
      (this.setHiddenConversations = (0,
      setHiddenConversations_js_1.setHiddenConversationsFactory)(e, this)),
      (this.setMute = (0, setMute_js_1.setMuteFactory)(e, this)),
      (this.setPinnedConversations = (0,
      setPinnedConversations_js_1.setPinnedConversationsFactory)(e, this)),
      (this.sharePoll = (0, sharePoll_js_1.sharePollFactory)(e, this)),
      (this.unblockUser = (0, unblockUser_js_1.unblockUserFactory)(e, this)),
      (this.undo = (0, undo_js_1.undoFactory)(e, this)),
      (this.undoFriendRequest = (0,
      undoFriendRequest_js_1.undoFriendRequestFactory)(e, this)),
      (this.updateActiveStatus = (0,
      updateActiveStatus_js_1.updateActiveStatusFactory)(e, this)),
      (this.updateAutoDeleteChat = (0,
      updateAutoDeleteChat_js_1.updateAutoDeleteChatFactory)(e, this)),
      (this.updateAutoReply = (0, updateAutoReply_js_1.updateAutoReplyFactory)(
        e,
        this,
      )),
      (this.updateCatalog = (0, updateCatalog_js_1.updateCatalogFactory)(
        e,
        this,
      )),
      (this.updateGroupSettings = (0,
      updateGroupSettings_js_1.updateGroupSettingsFactory)(e, this)),
      (this.updateHiddenConversPin = (0,
      updateHiddenConversPin_js_1.updateHiddenConversPinFactory)(e, this)),
      (this.updateLabels = (0, updateLabels_js_1.updateLabelsFactory)(e, this)),
      (this.updateLang = (0, updateLang_js_1.updateLangFactory)(e, this)),
      (this.updateProductCatalog = (0,
      updateProductCatalog_js_1.updateProductCatalogFactory)(e, this)),
      (this.updateProfile = (0, updateProfile_js_1.updateProfileFactory)(
        e,
        this,
      )),
      (this.updateQuickMessage = (0,
      updateQuickMessage_js_1.updateQuickMessageFactory)(e, this)),
      (this.updateSettings = (0, updateSettings_js_1.updateSettingsFactory)(
        e,
        this,
      )),
      (this.uploadAttachment = (0,
      uploadAttachment_js_1.uploadAttachmentFactory)(e, this)),
      (this.uploadProductPhoto = (0,
      uploadProductPhoto_js_1.uploadProductPhotoFactory)(e, this)),
      (this.votePoll = (0, votePoll_js_1.votePollFactory)(e, this)),
      (this.custom = (0, custom_js_1.customFactory)(e, this)));
  }
}
exports.API = API;
